Precaching
python-cachier/cachier pull request #111
Opened 2023-03-26 19:17 UTC by lordjabez

This PR enables the precaching of values without calling the underlying function.

2023-03-28 15:11 UTC, shaypal5 requested changes
Except for a tiny fix in the documentation of the feature, awesome PR!

2023-03-28 15:11 UTC, shaypal5 commented on README.rst
> +  foo.precache_value(2, 2, value_to_cache=5)
This should be `add.precache_value`...

2023-03-29 04:28 UTC, lordjabez commented
Fixed!

2023-03-29 19:14 UTC, shaypal5 approved these changes

2023-03-29 19:14 UTC, merged

2023-03-31 07:37 UTC, shaypal5 commented
Released in [v2.1.0](https://github.com/python-cachier/cachier/releases/tag/v2.1.0)