Ignore self parameter
python-cachier/cachier pull request #112
Opened 2023-03-26 19:26 UTC by lordjabez

@shaypal5 this change automatically ignores self if it's the first argument of a function's definition. This allows object methods to be cached across object instantiations. This has to be used with some care if the function result depends on the internal state of the object, but in my use case the class is an API client, and I want to be able to cache methods to avoid network round trips when the data is fresh.

Fixes #11 
Fixes #28

2023-03-28 15:13 UTC, shaypal5 approved these changes

2023-03-28 15:16 UTC, shaypal5 commented
Let's a **bold** note in our README regarding the issue you mentioned:
_"This has to be used with some care if the function result depends on the internal state of the object."_

Make it way clearer, maybe b yadding a line like "two different objects from the same class will share a cache for each of their methods!"

And a code example for a bad usage

2023-03-28 15:16 UTC, shaypal5 approved these changes
Let's add a **bold** note in our README regarding the issue you mentioned:
_"This has to be used with some care if the function result depends on the internal state of the object."_

Make it way clearer, maybe b yadding a line like "two different objects from the same class will share a cache for each of their methods!"

And a code example for a bad usage

2023-03-28 15:17 UTC, shaypal5 requested changes
Let's add a **bold** note in our README regarding the issue you mentioned:
_"This has to be used with some care if the function result depends on the internal state of the object."_

Make it way clearer, maybe b yadding a line like "two different objects from the same class will share a cache for each of their methods!"

And a code example for a bad usage

2023-03-29 04:42 UTC, lordjabez commented
@shaypal5 I updated the README. Let me know what you think.

2023-03-29 19:16 UTC, shaypal5 approved these changes

2023-03-30 02:51 UTC, merged

2023-03-31 07:38 UTC, shaypal5 commented
Released in [v2.1.0](https://github.com/python-cachier/cachier/releases/tag/v2.1.0)