Override stale after
python-cachier/cachier pull request #94
Opened 2022-11-28 23:39 UTC by louismartin

Allows user to override the stale_after parameter when calling the function.
I have a use case where I cache http get requests but I want to have different stale durations depending on the endpoint that I am calling.

## Usage
```
from datetime import timedelta
import time

from cachier import cachier

@cachier(stale_after=timedelta(days=1), pickle_reload=False)
def test():
    print("Inside function")
    return 1

print("First run")
test()
print("Second run")
test()
time.sleep(1)
print("Third run with overriden stale_after")
test(stale_after=timedelta(seconds=1))
```

```
First run
Inside function
Second run
Third run with overriden stale_after
Inside function
```

## Tests
Tests in `tests/test_pickle_core.py` pass

2022-12-02 11:24 UTC, shaypal5 commented
Ok. The repository has moved under a new GitHub organization, `python-cachier`, where you are a contributor.

Your PRs should now be able to successfully pull the secrets required by the `test` workflow to connect to the mongodb.com server used for tests, and thus you should be able to progress with PRs more independently (with working tests, pinging me only when you get to the code review and later merge phase, or if you need help, of course).

I've also added a flake8 lint job and fixed all flake8 errors except those in the `pickle_core.py` file, since you're working on it in you current 2 PRs.

**PLEASE re-base both PRs over the latest head.**

Please also fix all flake8 errors in this file in at least one of your PRs.

Thanks for contributing, friend! 😀

2022-12-24 17:00 UTC, shaypal5 commented
@louismartin What do you say? Contributing this should be easier now... :)

2022-12-29 16:24 UTC, louismartin commented
Hi @shaypal5 ,

Thanks a lot, that should make everything faster. Happy to contribute to cachier!
I'll update the PR when I get the time to look into it again if that's ok :)

2023-03-16 11:58 UTC, shaypal5 commented
> Hi @shaypal5 ,
> 
> Thanks a lot, that should make everything faster. Happy to contribute to cachier! I'll update the PR when I get the time to look into it again if that's ok :)

Was this ever updated? Should I pull this into a branch to have the tests actually run?

2023-03-19 19:35 UTC, louismartin commented
Hey @shaypal5 , 

No I have never gotten around running the tests for this again. 
Yes if you can pull into a branch that would be great!

2023-03-22 22:41 UTC, shaypal5 requested changes
This is missing two important things:
1. Tests.
2. Documentation.

2023-03-22 22:41 UTC, merged

2023-03-22 22:43 UTC, shaypal5 commented
I've pulled this into a its own branch to have tests run properly.
This is still missing a dedicated test and documentation.

Tests are running here:
https://github.com/python-cachier/cachier/actions/runs/4495148456

2023-03-22 22:46 UTC, shaypal5 commented
If everything passes, and you add a tests and some documentation, please open a new PR. :)